api:
    build: ./core
    container_name: 'newsp'
    links:
        - elasticsearch
        - mongo
    ports:
        - 5000:5000
    restart: always
    volumes:
        - .:/usr/src/app

    command:
        tail -f /dev/null


mongo:
    container_name: 'mongo'
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    image: mongo:latest
    ports:
        - 27017:27017
    restart: always
    volumes:
        - ./data/db:/data/db

    command: mongod --smallfiles --logpath=/dev/null


elasticsearch:
    container_name: 'elasticsearch'
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    restart: always
    ports:
        - 9200:9200
    ulimits:
        memlock:
            soft: -1
            hard: -1
        mem_limit: 1g
    user: elasticsearch
    volumes:
        - elasticsearch:/usr/share/elasticsearch/data